cmake_minimum_required(VERSION 4.1)
project(CPP_Level_1)

set(CMAKE_CXX_STANDARD 14)

include_directories(CPP-66-cppf10-matrix-fun-with-matrix-class)
include_directories(CPP-67-cppf11-profile-posts)
include_directories(CPP-38-cppf4-cat-class)
include_directories(CPP-39-cppf4-person-class)
include_directories(CPP-40-cppf4-person-class-with-bmi)
include_directories(CPP-41-cppf4-point-class)
include_directories(CPP-62-cppf9-dynamic-array-implementation)
include_directories(CPP-64-cppf9-grocery-list)

add_executable(CPP_Level_1
#        CPP-23-cpp-practice/main.cpp
#        CPP-24-cpp-structs-example/main.cpp
#        CPP-25-cppf1-chat-bot/main.cpp
#        CPP-26-cppf1-input-and-output-reference/main.cpp
#        CPP-27-cppf1-mad-libs/main.cpp
#        CPP-28-cppf1-primitive-types-and-strings-reference/main.cpp
#        CPP-29-cppf2-fizz-buzz/main.cpp
#        CPP-30-cppf2-for-loop-practice/main.cpp
#        CPP-31-cppf2-number-games/main.cpp
#        CPP-32-cppf2-rock-paper-scissors/main.cpp
#        CPP-33-cppf2-while-loop-practice/main.cpp
#        CPP-34-cppf3-function-practice/main.cpp
#        CPP-35-cppf3-number-guesser/main.cpp
#        CPP-36-cppf3-probability-functions/main.cpp
#        CPP-37-cppf3-rand-reference/main.cpp
#        CPP-38-cppf4-cat-class/cat.cpp
#        CPP-38-cppf4-cat-class/cat.h
#        CPP-38-cppf4-cat-class/main.cpp
#        CPP-39-cppf4-person-class/main.cpp
#        CPP-39-cppf4-person-class/person.cpp
#        CPP-39-cppf4-person-class/person.h
#        CPP-40-cppf4-person-class-with-bmi/main.cpp
#        CPP-40-cppf4-person-class-with-bmi/person.cpp
#        CPP-40-cppf4-person-class-with-bmi/person.h
#        CPP-41-cppf4-point-class/main.cpp
#        CPP-41-cppf4-point-class/point.cpp
#        CPP-41-cppf4-point-class/point.h
#        CPP-42-cppf5-pointer-error-examples/main.cpp
#        CPP-43-cppf5-pointer-practice/main.cpp
#        CPP-44-cppf5-pointers/main.cpp
#        CPP-45-cppf5-pointers-starter/main.cpp
#        CPP-46-cppf5-project-2-assembly-line/main.cpp
#        CPP-47-cppf6-chaos-monkeys/main.cpp
#        CPP-48-cppf6-defanging-a-website-url/main.cpp
#        CPP-49-cppf6-parameter-passing/main.cpp
#        CPP-50-cppf6-parameter-passing-introduction/main.cpp
#        CPP-51-cppf6-parameter-passing-starter/main.cpp
#        CPP-52-cppf7-array-basics-reference/main.cpp
        CPP-53-cppf7-array-practice/main.cpp
#        CPP-54-cppf7-array-practice-starter/main.cpp
#        CPP-55-cppf7-bank-accounts/main.cpp
#        CPP-56-cppf7-pointer-arithmetic-reference/main.cpp
#        CPP-57-cppf7-tic-tac-toe/main.cpp
#        CPP-58-cppf8-2d-array-practice/main.cpp
#        CPP-59-cppf8-bank-transactions/main.cpp
#        CPP-60-cppf8-two-dimensional-arrays-reference/main.cpp
#        CPP-61-cppf9-assembly-line/main.cpp
#        CPP-62-cppf9-dynamic-array-implementation/DynamicArray.cpp
#        CPP-62-cppf9-dynamic-array-implementation/DynamicArray.h
#        CPP-62-cppf9-dynamic-array-implementation/main.cpp
#        CPP-63-cppf9-dynamic-variables-reference/main.cpp
#        CPP-64-cppf9-grocery-list/DynamicArray.cpp
#        CPP-64-cppf9-grocery-list/DynamicArray.h
#        CPP-64-cppf9-grocery-list/GroceryList.cpp
#        CPP-64-cppf9-grocery-list/GroceryList.h
#        CPP-64-cppf9-grocery-list/main.cpp
#        CPP-65-cppf10-matrix-addition/main.cpp
#        CPP-66-cppf10-matrix-fun-with-matrix-class/main.cpp
#        CPP-66-cppf10-matrix-fun-with-matrix-class/matrix.cpp
#        CPP-66-cppf10-matrix-fun-with-matrix-class/matrix.h
#        CPP-67-cppf11-profile-posts/main.cpp
#        CPP-67-cppf11-profile-posts/profile.cpp
#        CPP-67-cppf11-profile-posts/profile.h
)
